Repository ublue-os/packages, pull requests merged in 2025-05, with the labels that each got.

#403 feat: add bluefin readymade configs for live ISOs
  packages/bluefin-readymade-config/bluefin-readymade-config.spec
  packages/bluefin-readymade-config/src/bento/bottom-right-dark.jxl
  packages/bluefin-readymade-config/src/bento/bottom-right.jxl
  packages/bluefin-readymade-config/src/bento/middle-left-dark.jxl
  packages/bluefin-readymade-config/src/bento/middle-left.jxl
  packages/bluefin-readymade-config/src/bento/top-right-dark.jxl
  packages/bluefin-readymade-config/src/bento/top-right.jxl
  packages/bluefin-readymade-config/src/repart/20-efi.conf
  packages/bluefin-readymade-config/src/repart/45-boot.conf
  packages/bluefin-readymade-config/src/repart/50-root.conf
Labels: size:M, lgtm

#404 fix: typo in bluefin-readymade-config package
  packages/bluefin-readymade-config/bluefin-readymade-config.spec
Labels: size:XS

#407 ublue-fastfetch: remove alias for hyfetch
  packages/ublue-fastfetch/src/vendor.fish
  packages/ublue-fastfetch/src/vendor.sh
Labels: size:XS, lgtm

#408 fix(ublue-builder): make failures be recognized as failures on the mock wrapper
  ublue-builder/mock-wrapper
Labels: bug, size:XS, lgtm

#406 fix(media-automount-udev): Simpler exclusion and handle windows parti…
  packages/ublue-os-media-automount-udev/99-media-automount.rules
  packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec
Labels: udev, size:S, lgtm

#410 refactor: set arch to noarch for most `ublue-*` packages
  packages/aurora/aurora.spec
  packages/bluefin-readymade-config/bluefin-readymade-config.spec
  packages/bluefin/bluefin.spec
  packages/ublue-bling/ublue-bling.spec
  packages/ublue-fastfetch/ublue-fastfetch.spec
  packages/ublue-motd/ublue-motd.spec
  packages/ublue-os-just/ublue-os-just.spec
  packages/ublue-rebase-helper/ublue-rebase-helper.spec
  packages/ublue-setup-services/ublue-setup-services.spec
Labels: size:M, lgtm

#415 fix(bluefin): update bluefin-readymade-config.spec
  packages/bluefin-readymade-config/bluefin-readymade-config.spec
Labels: size:XS, lgtm

#416 fix(logomenu): open up local PDF document
  staging/gnome-shell-extension-logo-menu/extension-boxbuddy.patch
  staging/gnome-shell-extension-logo-menu/gnome-shell-extension-logo-menu.spec
Labels: size:XS, lgtm

#411 feat: generate aarch64 tarballs for ublue-brew
  .github/workflows/brew-tarball.yml
Labels: brew, size:M, lgtm

#412 feat(ublue-brew): add aarch64 support and move to a sane directory structure
  packages/ublue-brew/src/etc/profile.d/brew-bash-completion.sh
  packages/ublue-brew/src/etc/profile.d/brew.sh
  packages/ublue-brew/src/etc/security/limits.d/30-brew-limits.conf
  packages/ublue-brew/src/usr/lib/systemd/system-preset/01-homebrew.preset
  packages/ublue-brew/src/usr/lib/systemd/system/brew-setup.service
  packages/ublue-brew/src/usr/lib/systemd/system/brew-update.service
  packages/ublue-brew/src/usr/lib/systemd/system/brew-update.timer
  packages/ublue-brew/src/usr/lib/systemd/system/brew-upgrade.service
  packages/ublue-brew/src/usr/lib/systemd/system/brew-upgrade.timer
  packages/ublue-brew/src/usr/lib/tmpfiles.d/homebrew.conf
  packages/ublue-brew/src/usr/share/fish/vendor_conf.d/ublue-brew.fish
  packages/ublue-brew/ublue-brew.spec
Labels: brew, size:S, lgtm

#421 feat(renovate): autoupdate fedora container
  .github/renovate.json5
Labels: enhancement, size:XS, lgtm

#420 fix(media-automount-udev): Typo in udev attr
  packages/ublue-os-media-automount-udev/99-media-automount.rules
  packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec
Labels: udev, size:XS, lgtm

#423 fix: ensure ublue-brew builds on hosts w/ different architectures from mock's runtime
  packages/ublue-brew/ublue-brew.spec
Labels: copr, size:S

#417 Add k8s related brews to kubernetes.Brewfile
  packages/bluefin/schemas/usr/share/ublue-os/homebrew/kubernetes.Brewfile
Labels: brew, size:XS, lgtm

#419 chore(just): move to new arch-toolbox tag
  packages/ublue-os-just/src/etc-distrobox/distrobox.ini
  packages/ublue-os-just/ublue-os-just.spec
Labels: just, size:XS, lgtm

#432 chore(ublue-brew): unlink gsettings
  packages/ublue-brew/src/usr/lib/systemd/system/brew-upgrade.service
  packages/ublue-brew/ublue-brew.spec
Labels: brew, size:XS, lgtm

#427 fix(motd): update secure boot url
  packages/ublue-setup-services/src/scripts/check-sb-key.sh
Labels: size:XS, lgtm

#435 chore: make Papers flatpak default for pdf
  packages/bluefin/bluefin.spec
  packages/bluefin/schemas/etc/skel/.config/mimeapps.list
Labels: size:XS, lgtm

#436 fix(bluefin): move mimeapps.list to /etc/xdg
  packages/bluefin/bluefin.spec
  packages/bluefin/schemas/etc/skel/.config/mimeapps.list
  packages/bluefin/schemas/etc/xdg/mimeapps.list
Labels: size:XS, lgtm

#418 feat: add aurora readymade config
  packages/aurora-readymade-config/aurora-readymade-config.spec
  packages/aurora-readymade-config/src/bento/bottom-right-dark.jxl
  packages/aurora-readymade-config/src/bento/bottom-right.jxl
  packages/aurora-readymade-config/src/bento/middle-left-dark.jxl
  packages/aurora-readymade-config/src/bento/middle-left.jxl
  packages/aurora-readymade-config/src/bento/top-right-dark.jxl
  packages/aurora-readymade-config/src/bento/top-right.jxl
  packages/aurora-readymade-config/src/repart/20-efi.conf
  packages/aurora-readymade-config/src/repart/45-boot.conf
  packages/aurora-readymade-config/src/repart/50-root.conf
Labels: enhancement, size:M, lgtm

#441 feat(ublue-builder): add handling for external coprs
  .github/workflows/build-package.yml
  Justfile
  ublue-builder/mock-wrapper
Labels: just, copr, size:M, lgtm

#440 feat: add anaconda branding for bluefin
  bluefin/fedora-logos/fedora-logos.spec
  bluefin/fedora-logos/src/anaconda/sidebar-bg.png
  bluefin/fedora-logos/src/anaconda/sidebar-logo.png
  bluefin/fedora-logos/src/anaconda/topbar-bg.png
  bluefin/fedora-logos/src/logos/fedora-gdm-logo.png
  bluefin/fedora-logos/src/logos/fedora-logo-icon.png
  bluefin/fedora-logos/src/logos/fedora-logo-small.png
  bluefin/fedora-logos/src/logos/fedora-logo-sprite.png
  bluefin/fedora-logos/src/logos/fedora-logo-sprite.svg
  bluefin/fedora-logos/src/logos/fedora-logo.png
  bluefin/fedora-logos/src/logos/fedora_logo_med.png
  bluefin/fedora-logos/src/logos/fedora_white_logo.svg
  bluefin/fedora-logos/src/logos/fedora_whitelogo.svg
  bluefin/fedora-logos/src/logos/fedora_whitelogo_med.png
  bluefin/fedora-logos/src/logos/system-logo-white.png
  bluefin/fedora-logos/src/logos/ublue-discourse.svg
  bluefin/fedora-logos/src/logos/ublue-docs.svg
  bluefin/fedora-logos/src/logos/ublue-update.svg
Labels: enhancement, copr, size:M, lgtm

#442 feat: add aurora branding for anaconda
  aurora/fedora-logos/fedora-logos.spec
  aurora/fedora-logos/src/anaconda/sidebar-bg.png
  aurora/fedora-logos/src/anaconda/sidebar-logo.png
  aurora/fedora-logos/src/anaconda/topbar-bg.png
  aurora/fedora-logos/src/logos/fedora-logo-small.png
  aurora/fedora-logos/src/logos/fedora-logo-sprite.png
  aurora/fedora-logos/src/logos/fedora-logo-sprite.svg
  aurora/fedora-logos/src/logos/fedora-logo.png
  aurora/fedora-logos/src/logos/fedora-logo.svg
  aurora/fedora-logos/src/logos/fedora_logo_med.png
  aurora/fedora-logos/src/logos/fedora_whitelogo.svg
  aurora/fedora-logos/src/logos/system-logo-white.png
  aurora/fedora-logos/src/logos/system-logo.png
  aurora/fedora-logos/src/logos/ublue-discourse.svg
  aurora/fedora-logos/src/logos/ublue-docs.svg
  aurora/fedora-logos/src/logos/ublue-update.svg
Labels: enhancement, size:M, lgtm

#443 fix(ublue-builder): typos that made build checks break
  .github/workflows/build-package.yml
  ublue-builder/mock-wrapper
Labels: bug, size:XS

#405 feat: add readymade/taidan and their deps to staging
  .github/workflows/build-package.yml
  staging/README.md
  staging/dart/dart.spec
  staging/helium-gtk-theme/helium-gtk-theme.spec
  staging/hydrogen-icon-theme/hydrogen-icon-theme.spec
  staging/libhelium/libhelium.spec
  staging/readymade/readymade.spec
  staging/sass/sass.spec
  staging/taidan/taidan.spec
Labels: enhancement, size:XL, lgtm

#439 fix(media-automount-udev): Better prevention of ntfs mounting
  packages/ublue-os-media-automount-udev/99-media-automount.rules
  packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec
  packages/ublue-os-media-automount-udev/ublue-os_udev_mount
Labels: udev, size:S, lgtm

#450 fix: add CSS for bluefin anaconda branding
  bluefin/fedora-logos/fedora-logos.spec
  bluefin/fedora-logos/src/anaconda/fedora.css
Labels: size:M

#447 feat(bluefin): put gnome firmware in utilities folder
  packages/bluefin/schemas/etc/dconf/db/distro.d/01-bluefin-folders
Labels: size:XS, lgtm

#451 fix: rename CSS to path used by installer
  bluefin/fedora-logos/src/anaconda/silverblue/fedora-silverblue.css
Labels: size:XS

#453 fix: rename CSS to path used by installer
  bluefin/fedora-logos/fedora-logos.spec
  bluefin/fedora-logos/src/anaconda/fedora-silverblue.css
  bluefin/fedora-logos/src/anaconda/silverblue/fedora-silverblue.css
Labels: size:M, lgtm

#454 feat(brew): add chezmoi to bluefin-cli
  packages/bluefin/schemas/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile
Labels: brew, size:XS, lgtm

#452 fix(bluefin): Fix buildpacks tap name in kubernetes.Brewfile
  packages/bluefin/schemas/usr/share/ublue-os/homebrew/kubernetes.Brewfile
Labels: brew, size:XS, lgtm

#456 feat(ublue-branding): add ublue-branding-logos package
  packages/aurora/aurora.spec
  packages/bluefin/bluefin.spec
  packages/bluefin/logos/ublue-discourse.svg
  packages/bluefin/logos/ublue-docs.svg
  packages/bluefin/logos/ublue-update.svg
  packages/ublue-branding/logos/ublue-discourse.svg
  packages/ublue-branding/logos/ublue-docs.svg
  packages/ublue-branding/logos/ublue-update.svg
  packages/ublue-branding/ublue-branding.spec
Labels: enhancement, size:L, lgtm

#458 fix(media-automount-udev): Preload database
  packages/ublue-os-media-automount-udev/99-media-automount.rules
  packages/ublue-os-media-automount-udev/is_in_fstab.sh
  packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec
  packages/ublue-os-media-automount-udev/ublue-os_udev_mount
Labels: udev, size:M, lgtm

#462 fix: Fix the branding
  bluefin/fedora-logos/src/anaconda/fedora-silverblue.css
Labels: size:XS

#460 feat(just): add fish ujust completion
  packages/ublue-os-just/ublue-os-just.spec
Labels: just, alternative-shells, size:XS, lgtm

#463 fix(aurora): fix branding
  aurora/fedora-logos/fedora-logos.spec
  aurora/fedora-logos/src/anaconda/fedora-kinoite.css
Labels: size:M, lgtm

#464 fix(aurora): fix errors for the branding
  aurora/fedora-logos/fedora-logos.spec
  aurora/fedora-logos/src/anaconda/fedora-silverblue.css
Labels: size:S, lgtm

#465 fix(aurora): resize images to fix installer branding
  aurora/fedora-logos/src/anaconda/sidebar-bg.png
  aurora/fedora-logos/src/anaconda/topbar-bg.png
Labels: size:XS, lgtm

#466 fix(aurora): bump package release to actually get resized wallpapers
  aurora/fedora-logos/fedora-logos.spec
Labels: size:XS

#468 fix: bump bluefin branding package
  bluefin/fedora-logos/fedora-logos.spec
Labels: size:XS, lgtm

#473 fix: css file fixes for anaconda branding
  aurora/fedora-logos/fedora-logos.spec
  aurora/fedora-logos/src/anaconda/fedora.css
Labels: size:S

#461 fix(ublue-setup-services): fix secure boot sb-state check
  packages/ublue-setup-services/src/scripts/check-sb-key.sh
Labels: services, size:XS, lgtm

#477 revert: "feat(ublue-branding): add ublue-branding-logos package"
  packages/aurora/aurora.spec
  packages/aurora/logos/ublue-discourse.svg
  packages/aurora/logos/ublue-docs.svg
  packages/aurora/logos/ublue-update.svg
  packages/bluefin/bluefin.spec
  packages/bluefin/logos/ublue-discourse.svg
  packages/bluefin/logos/ublue-docs.svg
  packages/bluefin/logos/ublue-update.svg
  packages/ublue-branding/ublue-branding.spec
Labels: size:L

#491 fix:: bump ublue-setup-services.spec
  packages/ublue-setup-services/ublue-setup-services.spec
Labels: size:XS, lgtm

#492 feat(staging): add `bazaar` package
  staging/README.md
  staging/bazaar/bazaar.spec
Labels: enhancement, size:M

#495 feat: Add PipeWire config enabling RAOP (AirPlay) on Aurora/Bluefin
  packages/aurora/aurora.spec
  packages/aurora/schemas/usr/share/pipewire/pipewire.conf.d/raop.conf
  packages/bluefin/bluefin.spec
  packages/bluefin/schemas/usr/share/pipewire/pipewire.conf.d/raop.conf
Labels: enhancement, size:S, lgtm

#498 chore(bazaar): bump to 70ccb329667a4d90662e7ec556b219b83f195023
  staging/bazaar/bazaar.spec
Labels: size:XS

#499 chore: configure renovate to manage global variables
  .github/renovate.json5
  staging/bazaar/bazaar.spec
  staging/readymade/readymade.spec
  staging/taidan/taidan.spec
Labels: size:XS, lgtm

#488 fix(media-automount-udev): Use service instead of udev
  packages/ublue-os-media-automount-udev/99-media-automount.rules
  packages/ublue-os-media-automount-udev/is_in_fstab.sh
  packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec
  packages/ublue-os-media-automount-udev/ublue-os-media-automount.conf
  packages/ublue-os-media-automount-udev/ublue-os-media-automount.py
  packages/ublue-os-media-automount-udev/ublue-os-media-automount.service
Labels: udev, services, size:L, lgtm

#502 feat: add bazaar to utils folder
  packages/bluefin/bluefin.spec
  packages/bluefin/schemas/etc/dconf/db/distro.d/01-bluefin-folders
Labels: size:XS, lgtm

#505 feat(bluefin): add search keybinding for bazaar
  packages/bluefin/bluefin.spec
  packages/bluefin/schemas/etc/dconf/db/distro.d/02-bluefin-keybindings
  packages/bluefin/schemas/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: enhancement, size:XS, lgtm

#506 chore(bluefin-schemas): remove nonexistent custom5
  packages/bluefin/bluefin.spec
  packages/bluefin/schemas/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: size:XS

#494 chore(aurora): better sidebar bg for anaconda branding
  aurora/fedora-logos/fedora-logos.spec
  aurora/fedora-logos/src/anaconda/fedora-logo-icon.png
  aurora/fedora-logos/src/anaconda/sidebar-bg.png
  aurora/fedora-logos/src/logos/fedora-logo-icon.png
Labels: size:XS

#513 fix(media-automount-udev): use getuid to check root
  packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec
  packages/ublue-os-media-automount-udev/ublue-os-media-automount.py
Labels: udev, size:S, lgtm

#516 chore(logo-menu): bump to 89e0e4d84b97e65f0787e195663090f157dd82ae and fix patch
  staging/gnome-shell-extension-logo-menu/gnome-shell-extension-logo-menu.spec
  staging/gnome-shell-extension-logo-menu/logos-entries.patch
Labels: size:S, lgtm

#519 fix(media-automount-udev): Start mounting before graphical session
  packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec
  packages/ublue-os-media-automount-udev/ublue-os-media-automount.service
Labels: udev, size:XS, lgtm

#521 fix(just): fix fish completion file directory
  packages/ublue-os-just/ublue-os-just.spec
Labels: alternative-shells, size:XS, lgtm

#523 fix: generate ujust shell completions on build time
  packages/ublue-os-just/ublue-os-just.spec
Labels: alternative-shells, size:M, lgtm

#501 chore: delete brew.sh from ublue-os-just
  packages/ublue-brew/ublue-brew.spec
  packages/ublue-os-just/src/etc-profile.d/brew.sh
  packages/ublue-os-just/ublue-os-just.spec
Labels: brew, size:S, lgtm

#532 fix: documentation url
  packages/ublue-bling/src/ublue-bling
Labels: documentation, size:XS, lgtm

#535 feat: Hide the overlay fs within fastfetch using the new hideFS param
  packages/aurora/aurora.spec
  packages/aurora/fastfetch/fastfetch.jsonc
  packages/bluefin/bluefin.spec
  packages/bluefin/fastfetch/fastfetch.jsonc
Labels: brew, size:S, lgtm

#543 feat(aurora): add remaining aurora-logos
  packages/aurora/aurora.spec
  packages/aurora/logos/distributor-logo-white.svg
  packages/aurora/logos/distributor-logo.svg
Labels: enhancement, size:S, lgtm

#555 fix: wallpaper month
  packages/bluefin/bluefin.spec
  packages/bluefin/wallpapers/images/06-bluefin-day.jxl
  packages/bluefin/wallpapers/images/06-bluefin-night.jxl
Labels: size:XS
