Repository ublue-os/packages, pull requests merged in 2025-03, with the labels that each got.

#267 ci: confirm if PR is safe to run + fix multi-file directories
  .github/workflows/build-package.yml
Labels: safe-to-run

#265 feat: Add ublue-os-media-automount-udev
  packages/ublue-os-media-automount-udev/60-media-automount.rules
  packages/ublue-os-media-automount-udev/is_in_fstab.sh
  packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec
Labels: safe-to-run

#270 fix(ublue-os-media-automount-udev): Add missing exec perms
  packages/ublue-os-media-automount-udev/is_in_fstab.sh
  packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec
Labels: safe-to-run

#271 feat(bluefin-branding): add bluefin-cli brewfiles
  packages/bluefin/bluefin.spec
  packages/bluefin/schemas/homebrew/bluefin-cli.Brewfile
  packages/bluefin/schemas/homebrew/kubernetes.Brewfile
Labels: safe-to-run

#272 feat: fully functional media-automount
  packages/ublue-os-media-automount-udev/99-media-automount.rules
  packages/ublue-os-media-automount-udev/is_in_fstab.sh
  packages/ublue-os-media-automount-udev/media-automount.conf
  packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec
Labels: safe-to-run

#280 chore: update renovate preset to best-practices
  .github/renovate.json5
Labels: size:XS, lgtm

#284 chore: switch to step-security/changed-files
  .github/workflows/build-package.yml
Labels: size:XS, lgtm

#292 docs: Add documentation link after enabling bling
  packages/ublue-bling/src/ublue-bling
Labels: documentation, size:XS, lgtm

#295 Fix ANSI code for unbold formatting; \e -> \033 for compatibility.
  packages/ublue-os-just/src/lib-ujust/libformatting.sh
Labels: just, size:XS, lgtm

#278 feat: Add pixi global install as option for ublue-bling
  packages/ublue-bling/src/ublue-bling
Labels: enhancement, safe-to-run, size:S, lgtm

#296 feat(ublue-brew): add update/upgrade services and timers
  packages/ublue-brew/src/systemd/01-homebrew.preset
  packages/ublue-brew/src/systemd/brew-update.service
  packages/ublue-brew/src/systemd/brew-update.timer
  packages/ublue-brew/src/systemd/brew-upgrade.service
  packages/ublue-brew/src/systemd/brew-upgrade.timer
  packages/ublue-brew/ublue-brew.spec
Labels: services, safe-to-run, brew, size:M, lgtm

#299 chore(kcm_ublue): bump version to 0.5.8
  packages/kcm_ublue/kcm_ublue.spec
Labels: safe-to-run, size:XS, lgtm

#301 fix: bump default mono size down to 16
  packages/bluefin/schemas/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: safe-to-run, size:XS, lgtm
