Repository ublue-os/packages, pull requests merged in 2025-04, with the labels that each got.

#303 feat: add bluefin fonts
  packages/bluefin/schemas/usr/share/ublue-os/homebrew/bluefin-fonts.Brewfile
Labels: enhancement, brew, size:XS, lgtm

#312 fix: formatting on CODEOWNERS file
  .github/CODEOWNERS
Labels: size:XS, lgtm

#313 Include additional nerd font
  packages/bluefin/schemas/usr/share/ublue-os/homebrew/bluefin-fonts.Brewfile
Labels: brew, size:XS, lgtm

#315 fix(bluefin): bluefin-fonts brewfile not getting recognized
  packages/bluefin/bluefin.spec
Labels: size:XS

#316 chore: Update CODEOWNERS
  .github/CODEOWNERS
Labels: size:S, lgtm

#317 revert: remove the safe-to-run tag
  .github/workflows/build-package.yml
Labels: size:XS

#306 feat(brew): add cdk8s and dagger to the k8s brewlist
  packages/bluefin/schemas/usr/share/ublue-os/homebrew/kubernetes.Brewfile
Labels: safe-to-run, brew, size:XS, lgtm

#232 chore: create backup container signing keys
  packages/ublue-os-signing/src/etc/pki/containers/ublue-os-backup.pub
  packages/ublue-os-signing/src/usr/etc/containers/policy.json
  packages/ublue-os-signing/ublue-os-signing.spec
Labels: size:S, lgtm

#321 fix(ublue-brew): include missing timer units
  packages/ublue-brew/ublue-brew.spec
Labels: copr, size:XS, lgtm

#320 ci(build): dont silently fail when spec files are not found + retry with network if failed building
  .github/workflows/build-package.yml
  Justfile
Labels: just, brew, size:M, lgtm

#333 fix: only install aurora-logos on aurora
  packages/aurora/aurora.spec
  packages/bluefin/bluefin.spec
Labels: copr, size:S, lgtm

#334 feat(bluefin): center new windows by default
  packages/bluefin/bluefin.spec
  packages/bluefin/schemas/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: enhancement, size:XS, lgtm

#329 feat(brew): add stress-ng
  packages/bluefin/schemas/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile
Labels: brew, size:XS, lgtm

#335 chore: bump release field of aurofin
  packages/aurora/aurora.spec
  packages/bluefin/bluefin.spec
Labels: copr, size:XS, lgtm

#293 feat: Add packit configuration
  .packit.yaml
  Justfile
  add_specs.sh
  packit.just
Labels: just, size:L, lgtm

#340 revert: packit configuration
  .packit.yaml
  Justfile
  add_specs.sh
  packit.just
Labels: just, size:L, lgtm

#331 chore: move more stuff from Aurora
  packages/aurora/aurora.spec
  packages/aurora/schemas/etc/geoclue/conf.d/99-beacondb.conf
  packages/aurora/schemas/usr/share/ublue-os/homebrew/aurora-cli.Brewfile
  packages/aurora/schemas/usr/share/ublue-os/homebrew/aurora-fonts.Brewfile
  packages/aurora/schemas/usr/share/ublue-os/homebrew/kubernetes.Brewfile
Labels: brew, size:M, lgtm

#345 ci: remove container pinning on GHA from renovate config and use wolfi for ublue builder manifest action
  .github/renovate.json5
  .github/workflows/builder.yml
Labels: size:S, lgtm

#343 fix(ublue-builder): make logs considerably more verbose
  ublue-builder/mock-wrapper
Labels: enhancement, size:XS, lgtm

#346 fix(brew): pack is a tap
  packages/bluefin/schemas/usr/share/ublue-os/homebrew/kubernetes.Brewfile
Labels: brew, size:XS, lgtm

#350 fix(ublue-builder): make it so build logs get printed after mock failure
  ublue-builder/mock-wrapper
Labels: size:XS, lgtm

#300 fix(bluefin-branding): remove that "enable Third Party Repositories?" page from GNOME initial setup
  packages/bluefin/bluefin.spec
  packages/bluefin/schemas/etc/gnome-initial-setup/vendor.conf
Labels: size:XS, lgtm

#338 feat: add search light to staging copr here instead of kyle's repo
  staging/gnome-shell-extension-searchlight/gnome-shell-extension-searchlight.spec
Labels: enhancement, copr, size:M, lgtm

#354 fix: searchlight has the wrong package name
  staging/gnome-shell-extension-search-light/gnome-shell-extension-search-light.spec
Labels: size:XS

#347 feat: add fw-fanctrl to staging copr
  staging/fw-ectool/framework-ectool.service
  staging/fw-ectool/framework-ectool.sh
  staging/fw-ectool/fw-ectool.sh
  staging/fw-ectool/fw-ectool.spec
  staging/fw-fanctrl/138-no-build.patch
  staging/fw-fanctrl/fw-fanctrl.spec
Labels: services, copr, size:L, lgtm

#355 fix(staging,logomenu): make sure logos are getting included on logomenu's package
  staging/gnome-shell-extension-logo-menu/gnome-shell-extension-logo-menu.spec
Labels: size:S, lgtm

#356 chore(aurora): bump versions to get new wallpaper correctly
  packages/aurora/aurora.spec
Labels: size:XS, lgtm

#358 feat(aurora): adjust to new textlogo from adelia.svg
  packages/aurora/aurora.spec
  packages/aurora/logos/fedora-logo-small.png
  packages/aurora/logos/fedora-logo.png
  packages/aurora/logos/fedora-logo.svg
  packages/aurora/logos/fedora_logo_med.png
  packages/aurora/logos/fedora_whitelogo.svg
  packages/aurora/plymouth/themes/spinner/kinoite-watermark.png
  packages/aurora/plymouth/themes/spinner/watermark.png
Labels: size:XS, lgtm

#360 feat: add readymade to favorites
  packages/bluefin/schemas/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: enhancement, size:XS, lgtm

#363 feat: add the coolest package (glorpfetch)
  packages/glorpfetch/glorpfetch.spec
  packages/glorpfetch/src/glorp.txt
  packages/glorpfetch/src/glorpfetch
  packages/glorpfetch/src/glorpfetch.jsonc
Labels: enhancement, size:L, lgtm

#366 fix(dx): delete staging/devpod directory
  .github/test/renovate/test_renovate.py
  staging/devpod/devpod.spec
Labels: size:M, lgtm

#357 chore: update caffeine for fedora 42
  staging/gnome-shell-extension-caffeine/gnome-shell-extension-caffeine.spec
Labels: size:XS, lgtm, gnome

#368 chore: remove Caffeine extension
  staging/gnome-shell-extension-caffeine/gnome-shell-extension-caffeine.spec
Labels: size:M, lgtm

#362 fix: fix spec file to be more portable
  packages/kcm_ublue/kcm_ublue.spec
Labels: size:M, lgtm

#364 feat: add ublue-os-dx-services package
  packages/ublue-os-dx-services/src/usr/lib/systemd/system-preset/54-ublue-os-dx-services.preset
  packages/ublue-os-dx-services/src/usr/lib/systemd/system/libvirt-workaround.service
  packages/ublue-os-dx-services/src/usr/lib/tmpfiles.d/libvirt-workaround.conf
  packages/ublue-os-dx-services/ublue-os-dx-services.spec
Labels: services, size:M, lgtm

#371 fix: rename ublue-os-dx-services to ublue-os-libvirt-workarounds
  packages/ublue-os-libvirt-workarounds/src/usr/lib/systemd/system-preset/54-ublue-os-libvirt-workarounds.preset
  packages/ublue-os-libvirt-workarounds/src/usr/lib/systemd/system/libvirt-workaround.service
  packages/ublue-os-libvirt-workarounds/src/usr/lib/tmpfiles.d/libvirt-workaround.conf
  packages/ublue-os-libvirt-workarounds/ublue-os-libvirt-workarounds.spec
Labels: services, size:XS, lgtm

#370 fix: fix glorps spawned on date
  packages/glorpfetch/glorpfetch.spec
  packages/glorpfetch/src/glorpfetch.jsonc
Labels: bug, size:XS, lgtm

#372 chore(bluefin): bump bluefin and all its subpackages
  packages/bluefin/bluefin.spec
Labels: size:S

#373 fix: add bluefin logo as `fedora-logo-icon` for Readymade
  packages/bluefin/bluefin.spec
  packages/bluefin/logos/fedora-logo-icon.png
Labels: size:XS, lgtm

#374 fix(ublue-os-udev-rules): update source of the Realtek 50-usb-realtek-net.rules file
  packages/ublue-os-udev-rules/src/udev-rules.d/50-usb-realtek-net.rules
  packages/ublue-os-udev-rules/ublue-os-udev-rules.spec
Labels: udev, size:M, lgtm

#375 Revert "fix(ublue-os-udev-rules): update source of the Realtek 50-usb-realtek-net.rules file (#374)
  packages/ublue-os-udev-rules/src/udev-rules.d/50-usb-realtek-net.rules
  packages/ublue-os-udev-rules/ublue-os-udev-rules.spec
Labels: udev, size:M, lgtm

#376 fix(bluefin,fastfetch): make sure forged date is right on composefs
  packages/bluefin/bluefin.spec
  packages/bluefin/fastfetch/fastfetch.jsonc
Labels: size:XS, lgtm

#379 fix(just): remove unused commands
  packages/ublue-os-just/src/recipes/00-default.just
Labels: just, size:S, lgtm

#381 Update search-light for Gnome 48
  staging/gnome-shell-extension-search-light/7193320dde849a06c3cee04f42450efb3c192874.patch
  staging/gnome-shell-extension-search-light/gnome-shell-extension-search-light.spec
Labels: size:M, lgtm

#383 fix(brew): install stress-ng not stress
  packages/aurora/schemas/usr/share/ublue-os/homebrew/aurora-cli.Brewfile
  packages/bluefin/schemas/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile
Labels: brew, size:XS, lgtm

#377 fix(aurora): Installation error when using kubernetes brewfile
  packages/aurora/aurora.spec
  packages/aurora/schemas/usr/share/ublue-os/homebrew/kubernetes.Brewfile
Labels: brew, size:XS, lgtm

#388 chore(aurora): add aurora maintainers as codeowners for aurora pkgs
  .github/CODEOWNERS
Labels: size:XS, lgtm

#385 chore(just): bump the spec
  packages/ublue-os-just/ublue-os-just.spec
Labels: just, size:XS, lgtm

#384 chore: remove gsconnect and supergfxctl-gex from staging
  staging/gnome-shell-extension-gsconnect/gnome-shell-extension-gsconnect-42-firewalld.patch
  staging/gnome-shell-extension-gsconnect/gnome-shell-extension-gsconnect.spec
  staging/gnome-shell-extension-gsconnect/nautilus-gsconnect.metainfo.xml
  staging/gnome-shell-extension-gsconnect/nemo-gsconnect.metainfo.xml
  staging/gnome-shell-extension-supergfxctl-gex/gnome-shell-extension-supergfxctl-gex.spec
Labels: copr, size:L, lgtm

#382 feat(brew): add syft and grype to the k8s toolset
  packages/bluefin/schemas/usr/share/ublue-os/homebrew/kubernetes.Brewfile
Labels: brew, size:XS, lgtm

#361 fix: unlink python in brew-upgrade.service
  packages/ublue-brew/src/systemd/brew-upgrade.service
Labels: services, brew, size:XS, lgtm

#387 chore(aurora): bump the versions
  packages/aurora/aurora.spec
Labels: size:S, lgtm

#389 fix(logomenu): set icon to 20px
  packages/bluefin/schemas/etc/dconf/db/distro.d/04-bluefin-logomenu-extension
Labels: size:XS, lgtm

#391 fix(aurora): fix kubernetes.Brewfile
  packages/aurora/aurora.spec
  packages/aurora/schemas/usr/share/ublue-os/homebrew/kubernetes.Brewfile
Labels: brew, size:XS, lgtm

#392 fix(aurora): fix typo in aurora-fonts.brewfile
  packages/aurora/schemas/usr/share/ublue-os/homebrew/aurora-fonts.Brewfile
Labels: brew, size:XS, lgtm

#394 chore: remove glorpfetch
  packages/glorpfetch/glorpfetch.spec
  packages/glorpfetch/src/glorp.txt
  packages/glorpfetch/src/glorpfetch
  packages/glorpfetch/src/glorpfetch.jsonc
Labels: size:L, lgtm

#395 fix(bluefin): update deps and bump spec to commit previous changes
  packages/bluefin/bluefin.spec
  packages/bluefin/wallpapers/gnome-background-properties/05-bluefin.xml
  packages/bluefin/wallpapers/images/05-bluefin-day.jxl
  packages/bluefin/wallpapers/images/05-bluefin-night.jxl
Labels: size:XS, lgtm

#398 feat(fw-fanctrl): automatically enable for Framework laptops
  staging/fw-fanctrl/99-fw-fanctrl.rules
  staging/fw-fanctrl/fw-fanctrl.spec
Labels: services, size:S, lgtm
