Repository ublue-os/packages, pull requests merged in 2025-07, with the labels that each got.

#672 fix(ublue-brew): add gcc to requires
  packages/ublue-brew/ublue-brew.spec
Labels: size:XS, lgtm

#673 chore(deps): update krunner-bazaar to 1.0.1
  packages/krunner-bazaar/krunner-bazaar.spec
Labels: size:XS, lgtm

#682 fix(bazaar): update .desktop file
  packages/bluefin/bluefin.spec
  packages/bluefin/schemas/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: size:XS, lgtm

#705 chore(deps): update krunner-bazaar to 1.0.4
  packages/krunner-bazaar/krunner-bazaar.spec
Labels: size:XS, lgtm

#710 chore(deps): update krunner-bazaar to 1.0.5
  packages/krunner-bazaar/krunner-bazaar.spec
Labels: size:XS, lgtm

#721 feat(brew): add bbrew
  packages/bluefin/schemas/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile
Labels: brew, size:XS, lgtm

#716 feat(aurora): generate multiple resolution logos at build time
  packages/aurora/aurora.spec
  packages/aurora/logos/fedora-logo-small.png
  packages/aurora/logos/fedora-logo-sprite.png
  packages/aurora/logos/fedora-logo-sprite.svg
  packages/aurora/logos/fedora-logo.png
  packages/aurora/logos/fedora_logo_med.png
  packages/aurora/logos/fedora_whitelogo.svg
  packages/aurora/logos/system-logo-white.png
  packages/aurora/logos/system-logo.png
Labels: enhancement, size:S, lgtm

#722 feat(aurora): add bold-brew to aurora-cli
  packages/aurora/aurora.spec
  packages/aurora/schemas/usr/share/ublue-os/homebrew/aurora-cli.Brewfile
Labels: ublue-cli, brew, size:XS, lgtm

#676 feat(ai): add bluefin-ai brewfile
  packages/bluefin/bluefin.spec
  packages/bluefin/schemas/usr/share/ublue-os/homebrew/bluefin-ai.Brewfile
Labels: brew, size:XS, lgtm

#730 feat(homebrew): k8s - k0s,k3s, kind AI - aichat, goose, clio CLI - carapace
  packages/bluefin/bluefin.spec
  packages/bluefin/schemas/usr/share/ublue-os/homebrew/bluefin-ai.Brewfile
  packages/bluefin/schemas/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile
  packages/bluefin/schemas/usr/share/ublue-os/homebrew/kubernetes.Brewfile
  packages/ublue-bling/src/bling.sh
  packages/ublue-bling/ublue-bling.spec
Labels: brew, size:S, lgtm

#731 feat(aurora): add brew tool carapace
  packages/aurora/aurora.spec
  packages/aurora/schemas/usr/share/ublue-os/homebrew/aurora-cli.Brewfile
Labels: ublue-cli, brew, size:XS, lgtm

#736 fix(bazaar): explictly require libdex 0.9.1
  staging/bazaar/bazaar.spec
Labels: bug, size:XS

#726 fix(bluefin): update discussions url
  packages/bluefin/schemas/usr/share/applications/discourse.desktop
Labels: size:XS, lgtm

#743 chore: bump kcm_ublue to 0.6.0
  packages/kcm_ublue/kcm_ublue.spec
Labels: size:XS, lgtm

#740 chore(media-automount-udev): remove old udev rule disable mechanism
  packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec
  packages/ublue-os-media-automount-udev/ublue-os-media-automount.py
Labels: udev, size:S, lgtm

#746 fix: syntax error k8s Brewfile
  packages/bluefin/schemas/usr/share/ublue-os/homebrew/kubernetes.Brewfile
Labels: brew, size:XS, lgtm

#754 chore: bump specfile version
  packages/bluefin/bluefin.spec
Labels: size:XS, lgtm

#760 feat(aurora): add profile pictures
  packages/aurora/aurora.spec
  packages/aurora/faces/lumina.png
  packages/aurora/faces/scope.png
  packages/aurora/faces/tina.png
  packages/aurora/faces/vincent.png
Labels: enhancement, size:S, lgtm

#764 feat(ci): add ci action for brewfiles lint
  .github/workflows/lint-brewfiles.yml
Labels: brew, size:S, lgtm

#768 feat(bluefin): set bazaar default for mimetype flatpakref
  packages/bluefin/bluefin.spec
  packages/bluefin/schemas/etc/xdg/mimeapps.list
Labels: enhancement, ublue-cli, size:XS, lgtm
