Repository ublue-os/packages, pull requests merged in 2025-06, with the labels that each got.

#562 fix(search-light): enable gnome 48 patches for epel 10 builds
  staging/gnome-shell-extension-search-light/gnome-shell-extension-search-light.spec
Labels: size:XS

#571 fix: bump logomenu
  staging/gnome-shell-extension-logo-menu/gnome-shell-extension-logo-menu.spec
Labels: size:XS, lgtm

#524 fix(media-automount-udev): ignore nonexisting entries in fstab
  packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec
  packages/ublue-os-media-automount-udev/ublue-os-media-automount.py
Labels: size:S, lgtm

#549 feat(aurora): add kde-config package
  packages/aurora/aurora.spec
  packages/aurora/kde-config/aurora.xml
  packages/aurora/kde-config/dev.getaurora.aurora.desktop/contents/defaults
  packages/aurora/kde-config/dev.getaurora.aurora.desktop/contents/plasmoidsetupscripts/org.kde.plasma.folder.js
  packages/aurora/kde-config/dev.getaurora.aurora.desktop/contents/plasmoidsetupscripts/org.kde.plasma.kickoff.js
  packages/aurora/kde-config/dev.getaurora.aurora.desktop/contents/plasmoidsetupscripts/org.kde.plasma.systemtray.js
  packages/aurora/kde-config/dev.getaurora.aurora.desktop/contents/previews/fullscreenpreview.jpg
  packages/aurora/kde-config/dev.getaurora.aurora.desktop/contents/previews/preview.png
  packages/aurora/kde-config/dev.getaurora.aurora.desktop/contents/previews/splash.png
  packages/aurora/kde-config/dev.getaurora.aurora.desktop/contents/splash/Splash.qml
  packages/aurora/kde-config/dev.getaurora.aurora.desktop/metadata.desktop
  packages/aurora/kde-config/dev.getaurora.aurora.desktop/metadata.json
Labels: enhancement, size:L, lgtm

#584 feat: add aurora recommended apps on discover
  packages/aurora/aurora.spec
  packages/aurora/kde-config/discover/featured.json
  packages/aurora/kde-config/discover/featuredurlrc
Labels: enhancement, size:S, lgtm

#589 chore: relocate sanoid spec to staging dir
  staging/sanoid/sanoid.spec
Labels: size:XS, lgtm

#599 feat: alias rl to ramalama
  packages/bluefin/schemas/etc/profile.d/ramalama.sh
Labels: size:XS, lgtm

#603 chore(aurora): remove universal blue logos
  packages/aurora/aurora.spec
  packages/aurora/logos/ublue-discourse.svg
  packages/aurora/logos/ublue-docs.svg
  packages/aurora/logos/ublue-update.svg
Labels: size:XS, lgtm

#619 fix: ensure libvirt group and libvirtdbus user/group are created
  packages/ublue-os-libvirt-workarounds/src/usr/lib/systemd/system-preset/54-ublue-os-libvirt-workarounds.preset
  packages/ublue-os-libvirt-workarounds/src/usr/lib/systemd/system/ublue-os-libvirt-workarounds.service
  packages/ublue-os-libvirt-workarounds/src/usr/lib/sysusers.d/ublue-os-libvirt-workarounds.conf
  packages/ublue-os-libvirt-workarounds/src/usr/lib/tmpfiles.d/ublue-os-libvirt-workarounds.conf
  packages/ublue-os-libvirt-workarounds/ublue-os-libvirt-workarounds.spec
Labels: services, size:S, lgtm

#586 feat(media-automount-udev): log reason for mounting skip
  packages/ublue-os-media-automount-udev/ublue-os-media-automount-udev.spec
  packages/ublue-os-media-automount-udev/ublue-os-media-automount.py
  packages/ublue-os-media-automount-udev/ublue-os-media-automount.service
Labels: udev, size:M, lgtm

#625 fix(bazaar): add gvfs dependency
  staging/bazaar/bazaar.spec
Labels: bug, size:XS, lgtm

#602 fix(ublue-setup-services): set service user as root
  packages/ublue-setup-services/src/services/ublue-system-setup.service
Labels: services, size:XS, lgtm

#637 chore(bazaar): add libsoup and json-glib deps, remove gvfs
  staging/bazaar/bazaar.spec
Labels: size:XS, lgtm

#638 feat: switch bluefin to bazaar
  packages/bluefin/schemas/etc/dconf/db/distro.d/01-bluefin-folders
  packages/bluefin/schemas/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: enhancement, ublue-cli, size:XS, lgtm

#647 fix: bump spec
  packages/bluefin/bluefin.spec
Labels: size:XS, lgtm

#651 feat(aurora): add start-here logo
  packages/aurora/aurora.spec
Labels: size:XS, lgtm

#659 feat: add krunner-bazaar
  packages/krunner-bazaar/krunner-bazaar.spec
Labels: enhancement, size:M, lgtm

#661 feat(ujust): add more aliases to davinci-resolve
  packages/ublue-os-just/src/recipes/30-distrobox.just
  packages/ublue-os-just/ublue-os-just.spec
Labels: just, size:S, lgtm
