Repository ublue-os/packages, pull requests merged in 2025-08, with the labels that each got.

#481 feat: Use the new Adwaita font instead of Inter
  packages/bluefin/bluefin.spec
  packages/bluefin/schemas/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: enhancement, size:XS, lgtm

#770 feat(bluefin): add red tulip wallpaper
  packages/bluefin/bluefin.spec
  packages/bluefin/wallpapers/gnome-background-properties/xe_red_tulip.xml
  packages/bluefin/wallpapers/images/xe_red_tulip.jxl
Labels: enhancement, size:S, lgtm

#778 chore: add bootc upgrade to sudoers file
  packages/ublue-polkit-rules/src/etc/sudoers.d/001-bootc
Labels: services, size:XS, lgtm

#780 feat: Allow modifying atuin flags in bling.fish
  packages/ublue-bling/src/bling.fish
Labels: alternative-shells, size:XS, lgtm

#783 feat(aurora): add phlip and echo to faces package
  packages/aurora/aurora.spec
  packages/aurora/faces/echo.png
  packages/aurora/faces/phlip.png
Labels: enhancement, size:XS, lgtm

#787 chore(aurora): update white-circle logos
  packages/aurora/aurora.spec
  packages/aurora/logos/distributor-logo-darkwhite-circle.svg
  packages/aurora/logos/distributor-logo-white-circle.svg
Labels: ublue-cli, size:S, lgtm

#799 chore(ublue-bling): bump version
  packages/ublue-bling/ublue-bling.spec
Labels: autorelease: pending, size:XS, lgtm

#805 chore: bump brew runner
  .github/workflows/lint-brewfiles.yml
Labels: brew, size:XS, lgtm

#806 schemas(bluefin): bump bluefin gnome schemas
  packages/bluefin/bluefin.spec
Labels: size:XS, lgtm, gnome

#829 fix({aurora,bluefin}): move pipewire `raop` config file to `/etc` instead of `/usr/share` to allow disabling the raop module
  packages/aurora/aurora.spec
  packages/aurora/schemas/etc/pipewire/pipewire.conf.d/raop.conf
  packages/bluefin/bluefin.spec
  packages/bluefin/schemas/etc/pipewire/pipewire.conf.d/raop.conf
Labels: services, size:S, lgtm

#827 feat(aurora): add aurora ai tools
  packages/aurora/aurora.spec
  packages/aurora/schemas/usr/share/ublue-os/homebrew/aurora-ai.Brewfile
Labels: enhancement, brew, size:S, lgtm

#835 chore(deps): update krunner-bazaar to 1.2.1
  packages/krunner-bazaar/krunner-bazaar.spec
Labels: size:XS, lgtm

#836 fix: remove claude-code from aurora-ai recipe
  packages/aurora/aurora.spec
  packages/aurora/schemas/usr/share/ublue-os/homebrew/aurora-ai.Brewfile
Labels: brew, size:XS, lgtm

#816 feat(aurora): add proper sddm theme
  packages/aurora/aurora.spec
  packages/aurora/kde-config/sddm/01-breeze-aurora/Background.qml
  packages/aurora/kde-config/sddm/01-breeze-aurora/KeyboardButton.qml
  packages/aurora/kde-config/sddm/01-breeze-aurora/Login.qml
  packages/aurora/kde-config/sddm/01-breeze-aurora/Main.qml
  packages/aurora/kde-config/sddm/01-breeze-aurora/SessionButton.qml
  packages/aurora/kde-config/sddm/01-breeze-aurora/metadata.desktop
  packages/aurora/kde-config/sddm/01-breeze-aurora/preview.png
  packages/aurora/kde-config/sddm/01-breeze-aurora/theme.conf
  packages/aurora/plymouth/themes/spinner/kinoite-watermark.png
  packages/aurora/plymouth/themes/spinner/watermark.png
Labels: size:XL, lgtm

#860 fix(aurora): plymouth typo
  packages/aurora/aurora.spec
  packages/aurora/kde-config/sddm/01-breeze-aurora/faces/.face.icon
Labels: bug, size:M, lgtm

#866 feat: remove toolbox ujust files
  packages/ublue-os-just/src/etc-toolbox/toolbox.ini
  packages/ublue-os-just/src/recipes/31-toolbox.just
  packages/ublue-os-just/ublue-os-just.spec
Labels: just, size:M, lgtm
